# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    touch web.config
    touch server.js
    mkdir dist
  displayName: 'Mock file creation'
  
- script: |
    Compress-Archive -Path .\dist, web.config, server.js -DestinationPath $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  displayName: 'Archive Files'
